---
resources:
  - name: repository-with-a-version-bump
    type: git
    source:
      branch: main
      # sshで認証するため、uriはsshのuriに設定する必要がある(httpsだと正常動作しない）
      uri: git@github.com:moriyamaES/cicd-repo-for-source-code.git
      # GitHubに接続するための秘密鍵はVaultで管理
      private_key: ((private-key))
  - name: repository-of-script
    type: git
    source:
      uri: git@github.com:moriyamaES/cicd-repo-for-manifesto.git
      branch: main
jobs:
  - name: bump-version
    plan:
      - get: repository-with-a-version-bump
      - task: bump-version
        config:
          platform: linux
          image_resource:
            type: docker-image
            # bashとgitが実行できるコンテナをpull
            source: {repository: getourneau/alpine-bash-git}
          # nputsとoutputsは、同じ名前にしないと正常動作しない模様
          inputs:
            - name: repository-with-a-version-bump
          outputs:
            - name: repository-with-a-version-bump
          params:
            BUMP_TYPE: ((bump-type))
          run:
            path: repository-of-script/concourse/pipline/bump-version.sh

      # 以下のPUTで、ローカルリポジトリからリポジトリへのpushを実行するため、git pushの実行は不要。
      - put: repository-with-a-version-bump
        params:
          repository: repository-with-a-version-bump
